name: snake

on: [push, pull_request]

jobs:

  snakes:
    runs-on: rocky:9
    steps:
      - name: script
        run: |
          chmod 777 updates.sh
          ./updates.s
  python:
    runs-on: rocky:9
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v6
      with:
        python-version: '3.13' 
    - run: python my_script.py

  docker:
    runs-on: rocky:9
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: user/app:latest

  
